// <auto-generated />
using System;
using CasmanSln.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasmanSln.Migrations
{
    [DbContext(typeof(CasmanDbContext))]
    partial class CasmanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasmanSln.Models.Case", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("case_id");

                    b.Property<DateTime?>("AdvCloseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Adv_Close_Date");

                    b.Property<string>("AreaCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area_code");

                    b.Property<string>("CaseCat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_cat");

                    b.Property<string>("CaseClass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_class");

                    b.Property<string>("CaseCreateSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Case_Create_Source");

                    b.Property<string>("CaseDocumentStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Case_Document_Status");

                    b.Property<bool?>("CaseNotesAvail")
                        .HasColumnType("bit")
                        .HasColumnName("case_notes_avail");

                    b.Property<bool?>("CaseOfInt")
                        .HasColumnType("bit")
                        .HasColumnName("case_of_int");

                    b.Property<string>("CaseStat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_stat");

                    b.Property<string>("CaseType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_type");

                    b.Property<string>("CaseUri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_uri");

                    b.Property<DateTime?>("ClaimDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLAIM_DATE");

                    b.Property<string>("ClfnCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clfn_code");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("close_date");

                    b.Property<string>("Cru")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cru");

                    b.Property<DateTime?>("DateLastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_last_updated");

                    b.Property<string>("DoiStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOI_Status");

                    b.Property<string>("FacPostcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fac_postcode");

                    b.Property<string>("FileClassCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_class_code");

                    b.Property<string>("FirstPgLoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_pg_loc");

                    b.Property<bool?>("HaAprvd")
                        .HasColumnType("bit")
                        .HasColumnName("ha_aprvd");

                    b.Property<string>("HaFpcName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ha_fpc_name");

                    b.Property<string>("HptlLoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hptl_loc");

                    b.Property<DateTime?>("IncdtDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("incdt_date");

                    b.Property<string>("LegalCaseDocumentStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Legal_case_Document_Status");

                    b.Property<int?>("LockNo")
                        .HasColumnType("int")
                        .HasColumnName("lock_no");

                    b.Property<string>("MduLiability")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mdu_liability");

                    b.Property<string>("MduReinsHal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mdureins_hal");

                    b.Property<string>("MduUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mdu_unit");

                    b.Property<string>("MficheNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mfiche_no");

                    b.Property<string>("MissedKpiCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MissedKPI_Code");

                    b.Property<string>("Offc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("offc");

                    b.Property<string>("OldCaseType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_case_type");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("open_date");

                    b.Property<string>("PracAreaCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_area_code");

                    b.Property<string>("ProdType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prodType");

                    b.Property<bool?>("PymntDataAvail")
                        .HasColumnType("bit")
                        .HasColumnName("pymnt_data_avail");

                    b.Property<bool?>("RedactCase")
                        .HasColumnType("bit")
                        .HasColumnName("redact_case");

                    b.Property<string>("RedactCaseRule")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("redact_case_rule");

                    b.Property<bool?>("RefDataAvail")
                        .HasColumnType("bit")
                        .HasColumnName("ref_data_avail");

                    b.Property<bool?>("ReinsDataAvail")
                        .HasColumnType("bit")
                        .HasColumnName("reins_data_avail");

                    b.Property<DateTime?>("RetentionActionedDT")
                        .HasColumnType("datetime2")
                        .HasColumnName("RetentionActionedDT");

                    b.Property<string>("RetentionActionedPolicyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RetentionActionedPolicyName");

                    b.Property<string>("ScrtUsr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scrt_usr");

                    b.Property<string>("SecondScrtUsr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("second_scrt_usr");

                    b.Property<bool?>("SharedCase")
                        .HasColumnType("bit")
                        .HasColumnName("shared_case");

                    b.Property<string>("SpcltyMajCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("spclty_maj_code");

                    b.Property<string>("SpcltyMinCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("spclty_min_code");

                    b.Property<string>("SubsidId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subsid_id");

                    b.Property<string>("ThirdScrtUsr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("third_scrt_usr");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.Property<int?>("YearOfCase")
                        .HasColumnType("int")
                        .HasColumnName("YearOfCase");

                    b.HasKey("CaseId");

                    b.ToTable("t_case");
                });

            modelBuilder.Entity("CasmanSln.Models.CasePractioner", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("case_id");

                    b.Property<string>("CharmPolicyNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CharmPolicyNumber");

                    b.Property<string>("CharmPolicyVersion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CharmPolicyVersion");

                    b.Property<string>("CoverType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cover_type");

                    b.Property<DateTime?>("DateClaimMade")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_claim_made");

                    b.Property<DateTime?>("DateInvolved")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_involved");

                    b.Property<DateTime?>("DateLastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_last_updated");

                    b.Property<DateTime?>("DateNonIrishClaimMade")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_nonirish_claim_made");

                    b.Property<DateTime?>("DateNotified")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_notified");

                    b.Property<bool?>("DdrApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("DDRApplicable");

                    b.Property<string>("DdrCoverType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DDRCoverType");

                    b.Property<string>("DiscReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Disc_Reason");

                    b.Property<string>("DonPolSelection")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DON_Polselection");

                    b.Property<string>("GroupNum")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_num");

                    b.Property<string>("GroupType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_type");

                    b.Property<int?>("LockNo")
                        .HasColumnType("int")
                        .HasColumnName("lock_no");

                    b.Property<bool?>("MemberEntitled")
                        .HasColumnType("bit")
                        .HasColumnName("Member_Entitled");

                    b.Property<DateTime?>("MemberEntitledDateModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("Member_Entitled_DateModified");

                    b.Property<string>("OrgName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("orgname");

                    b.Property<string>("PracDefOrg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_def_org");

                    b.Property<string>("PracFirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_first_name");

                    b.Property<string>("PracInit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_init");

                    b.Property<string>("PracInvl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_invl");

                    b.Property<string>("PracLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_last_name");

                    b.Property<string>("PracNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_num");

                    b.Property<string>("PracRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_role");

                    b.Property<int?>("PracSeqNum")
                        .HasColumnType("int")
                        .HasColumnName("prac_seq_num");

                    b.Property<string>("PracSex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_sex");

                    b.Property<string>("PracSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_source");

                    b.Property<string>("PracTow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_tow");

                    b.Property<bool?>("PrivateGpClaims")
                        .HasColumnType("bit")
                        .HasColumnName("PrivateGPClaims");

                    b.Property<string>("ProdRefNoSubSegCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProdRefNo_SubSegCode");

                    b.Property<string>("SubsidId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subsid_id");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("CaseId");

                    b.ToTable("t_case_prac");
                });
#pragma warning restore 612, 618
        }
    }
}
