// <auto-generated />
using System;
using CasmanSln.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasmanSln.Migrations
{
    [DbContext(typeof(CasmanDbContext))]
    [Migration("20250821090311_indem2")]
    partial class indem2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasmanSln.Models.Area", b =>
                {
                    b.Property<string>("AreaDesc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AdultLimitationMonths")
                        .HasColumnType("int");

                    b.Property<string>("AreaJurisdiction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrainDamageLimitationMonths")
                        .HasColumnType("int");

                    b.Property<int?>("ChildrenLimitationMonths")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryTax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtryNominalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortColumn")
                        .HasColumnType("int");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("AreaDesc");

                    b.ToTable("t_area");
                });

            modelBuilder.Entity("CasmanSln.Models.Case", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("case_id");

                    b.Property<string>("CaseCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_cat");

                    b.Property<string>("CaseCreateSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Case_Create_Source");

                    b.Property<string>("CasePractice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_prac");

                    b.Property<string>("CaseSpeciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_spl");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_type");

                    b.Property<string>("CaseUri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_uri");

                    b.Property<DateTime?>("ClaimDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLAIM_DATE");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("close_date");

                    b.Property<DateTime?>("DateLastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_last_updated");

                    b.Property<DateTime?>("IncdtDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("incdt_date");

                    b.Property<string>("LegalCaseDocumentStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Legal_case_Document_Status");

                    b.Property<string>("MduUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mdu_unit");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("open_date");

                    b.Property<string>("SecondScrtUsr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("second_scrt_usr");

                    b.Property<string>("SubsidId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subsid_id");

                    b.Property<string>("ThirdScrtUsr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("third_scrt_usr");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.Property<int?>("YearOfCase")
                        .HasColumnType("int")
                        .HasColumnName("YearOfCase");

                    b.HasKey("CaseId");

                    b.ToTable("t_case");
                });

            modelBuilder.Entity("CasmanSln.Models.CasePractioner", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("case_id");

                    b.Property<DateTime?>("DateClaimMade")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_claim_made");

                    b.Property<DateTime?>("DateInvolved")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_involved");

                    b.Property<DateTime?>("DateLastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_last_updated");

                    b.Property<DateTime?>("DateNotified")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_notified");

                    b.Property<string>("PracDefOrg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_def_org");

                    b.Property<string>("PracFirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_first_name");

                    b.Property<string>("PracInit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_init");

                    b.Property<string>("PracInvl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_invl");

                    b.Property<string>("PracLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_last_name");

                    b.Property<string>("PracNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_num");

                    b.Property<string>("PracRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_role");

                    b.Property<int?>("PracSeqNum")
                        .HasColumnType("int")
                        .HasColumnName("prac_seq_num");

                    b.Property<string>("PracSex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_sex");

                    b.Property<string>("PracTow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_tow");

                    b.Property<string>("SubsidId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subsid_id");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("CaseId");

                    b.ToTable("t_case_prac");
                });

            modelBuilder.Entity("CasmanSln.Models.CaseType", b =>
                {
                    b.Property<string>("case_type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("type_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("valid")
                        .HasColumnType("bit");

                    b.HasKey("case_type");

                    b.ToTable("t_caseType");
                });

            modelBuilder.Entity("CasmanSln.Models.Category", b =>
                {
                    b.Property<int>("Category_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_no"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cat_nominal_code")
                        .HasColumnType("int");

                    b.Property<int>("valid")
                        .HasColumnType("int");

                    b.HasKey("Category_no");

                    b.ToTable("t_Category");
                });

            modelBuilder.Entity("CasmanSln.Models.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryNominalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("CountryCode");

                    b.ToTable("t_country");
                });

            modelBuilder.Entity("CasmanSln.Models.Department", b =>
                {
                    b.Property<string>("DeptId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("t_dept");
                });

            modelBuilder.Entity("CasmanSln.Models.Indemnifier", b =>
                {
                    b.Property<int>("Def_Org")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Def_Org"));

                    b.Property<int?>("Def_Order")
                        .HasColumnType("int");

                    b.Property<string>("Def_Org_Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Def_Org");

                    b.ToTable("t_def_org");
                });

            modelBuilder.Entity("CasmanSln.Models.MduLiability", b =>
                {
                    b.Property<string>("case_type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("liab_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mdu_liability")
                        .HasColumnType("int");

                    b.Property<bool>("valid")
                        .HasColumnType("bit");

                    b.HasKey("case_type");

                    b.ToTable("t_mduLiability");
                });

            modelBuilder.Entity("CasmanSln.Models.PracArea", b =>
                {
                    b.Property<int>("prac_area_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prac_area_code"));

                    b.Property<string>("prac_area_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("valid")
                        .HasColumnType("bit");

                    b.HasKey("prac_area_code");

                    b.ToTable("t_pracArea");
                });

            modelBuilder.Entity("CasmanSln.Models.Specialty", b =>
                {
                    b.Property<string>("SpcltyCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ClaimsUse")
                        .HasColumnType("bit");

                    b.Property<bool>("MemUse")
                        .HasColumnType("bit");

                    b.Property<string>("SpcltyDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpcltyCode");

                    b.ToTable("t_specialties");
                });

            modelBuilder.Entity("CasmanSln.Models.Staff", b =>
                {
                    b.Property<string>("StaffNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeptId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("StaffNo");

                    b.ToTable("t_staff");
                });

            modelBuilder.Entity("CasmanSln.Models.adv_team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Dept_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("t_adv_team");
                });

            modelBuilder.Entity("CasmanSln.Models.app_user", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("appId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("t_app_user");
                });
#pragma warning restore 612, 618
        }
    }
}
