// <auto-generated />
using System;
using CasmanSln.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasmanSln.Migrations
{
    [DbContext(typeof(CasmanDbContext))]
    partial class CasmanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasmanSln.Models.Case", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("case_id");

                    b.Property<string>("CaseCreateSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Case_Create_Source");

                    b.Property<string>("CaseUri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_uri");

                    b.Property<DateTime?>("ClaimDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLAIM_DATE");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("close_date");

                    b.Property<DateTime?>("DateLastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_last_updated");

                    b.Property<DateTime?>("IncdtDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("incdt_date");

                    b.Property<string>("LegalCaseDocumentStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Legal_case_Document_Status");

                    b.Property<string>("MduUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mdu_unit");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("open_date");

                    b.Property<string>("SecondScrtUsr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("second_scrt_usr");

                    b.Property<string>("SubsidId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subsid_id");

                    b.Property<string>("ThirdScrtUsr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("third_scrt_usr");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.Property<int?>("YearOfCase")
                        .HasColumnType("int")
                        .HasColumnName("YearOfCase");

                    b.HasKey("CaseId");

                    b.ToTable("t_case");
                });

            modelBuilder.Entity("CasmanSln.Models.CasePractioner", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("case_id");

                    b.Property<DateTime?>("DateClaimMade")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_claim_made");

                    b.Property<DateTime?>("DateInvolved")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_involved");

                    b.Property<DateTime?>("DateLastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_last_updated");

                    b.Property<DateTime?>("DateNotified")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_notified");

                    b.Property<string>("PracDefOrg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_def_org");

                    b.Property<string>("PracFirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_first_name");

                    b.Property<string>("PracInit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_init");

                    b.Property<string>("PracInvl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_invl");

                    b.Property<string>("PracLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_last_name");

                    b.Property<string>("PracNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_num");

                    b.Property<string>("PracRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_role");

                    b.Property<int?>("PracSeqNum")
                        .HasColumnType("int")
                        .HasColumnName("prac_seq_num");

                    b.Property<string>("PracSex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_sex");

                    b.Property<string>("PracTow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prac_tow");

                    b.Property<string>("SubsidId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subsid_id");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("CaseId");

                    b.ToTable("t_case_prac");
                });
#pragma warning restore 612, 618
        }
    }
}
